version: "3.9"

services:
  app:
    build:
      context: .
    container_name: railsnew_app
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/railsnew_development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bin/rails server -b 0.0.0.0 -p 3000
  db:
    image: postgres:17.2
    container_name: railsnew_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: railsnew_development
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
